### PR TITLE
fetch missions

### PR DESCRIPTION
**Pull request by aliveGUY**
# Fetching Mission 

## We should manage app structure better. I think each component should fetch its own data.
image
## Is nearly impossible to work with multiply reducers for some reason. I'm just retrieving the already existing state here :
image
image

1. versions are fine
2. hooks used like in the documentation
3. the probe might be an overall app structure

### CODE REVIEW

**Comment by aliveGUY** [comment]
# Updatae
## It works only if in <App /> used
image

# *Please consider putting yours in a separate file.*

**Comment by wandergithub** [comment]
image
1. Refactored the fetch rocket code and moved it to a separate module. But still have to use an async function.

**Comment by aliveGUY** [comment]
# Main changes: 
## Sorted Hooks
image

**Review by wandergithub — APPROVED** [review]
### Well done ✔️ 
✔️ Missions fetched
✔️ Clean code
✔️ Works perfect
⚠️ console.log

I'll proceed and merge the PR. As it seems, everything it's working well.

**Pull request merged**
